[tool.poetry]
name = "tujiang"
version = "0.0.1"
description = "兔酱 - 基于 NoneBot2 + OneBot v11 的 QQ 机器人"
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.4-beta.0"

[tool.pytest.ini_options]
addopts = '-p no:warnings'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
